[deploy]
startCommand = "python -m backend.services.backup_users backup && python -m backend.services.import_products && python -m backend.services.sync_images && python -m backend.services.import_clients && python -m backend.services.backup_users restore && python start_all.py"

[[mounts]]
mountPath = "/data"
