#!/usr/bin/env python3
"""Backfill daily_fx_rates with CBU (Central Bank of Uzbekistan) official
USD/UZS rates from the cbu_rates_*.xls exports in the parent Finances/ folder.

Why: daily_fx_rates (user-uploaded via /fxrate) only starts 2026-04-01. Every
Business Overview prior-year (2025) period therefore fell back to a flat 12,000
rate — but the real CBU rate in early 2025 was ~12,900 (~7% off). The uploaded
2026-04-01 rate (12,200) matches CBU (12,194) to within 0.05%, so the CBU series
is basis-consistent with the existing manual rows.

Safe + reversible:
  - INSERT OR IGNORE — never overwrites an existing (rate_date, currency_pair)
    row, so user-uploaded rates from 2026-04-01 onward are preserved.
  - All inserted rows are tagged source='cbu_official'.
  - Undo: DELETE FROM daily_fx_rates WHERE source='cbu_official';

The CBU .xls files are OLE2/BIFF but trip xlrd's stream-corruption check, so we
open with ignore_workbook_corruption=True.

Usage:
  # Apply directly to a DB (local / snapshot):
  python tools/backfill_fx_rates.py --db data/catalog.db

  # Emit a self-contained script with the rates embedded (no xlrd / no .xls
  # needed on the target) — for running on Railway prod via railway ssh:
  python tools/backfill_fx_rates.py --emit-script > /tmp/fx_backfill_prod.py
"""
import argparse
import os
import re
import sqlite3
import sys

CBU_FILES = [
    "Finances/cbu_rates_2025-01-01-2026-01-01_ru.xls",
    "Finances/cbu_rates_2026-01-01-2026-04-01_ru.xls",
]
CURRENCY_PAIR = "USD_UZS"
SOURCE = "cbu_official"
UPLOADED_BY = "CBU backfill"


def _parent_root() -> str:
    # tools/ lives in telegram-catalog/; the Finances/ folder is one level up.
    return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def parse_rates() -> dict:
    """Return {date_iso: rate_float} parsed from the CBU xls exports."""
    import xlrd

    root = _parent_root()
    rows: dict[str, float] = {}
    for rel in CBU_FILES:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            raise FileNotFoundError(path)
        wb = xlrd.open_workbook(path, ignore_workbook_corruption=True)
        sh = wb.sheet_by_index(0)
        for r in range(sh.nrows):
            d = sh.cell_value(r, 0)
            if not isinstance(d, str):
                continue
            d = d.strip()
            if not re.match(r"^\d{4}-\d{2}-\d{2}$", d):
                continue
            rate = float(sh.cell_value(r, 2))
            if not (8000 < rate < 20000):  # sanity guard
                print(f"  skip out-of-range {d} {rate}", file=sys.stderr)
                continue
            rows[d] = rate
    return rows


def apply_to_db(db_path: str, rows: dict) -> tuple[int, int]:
    conn = sqlite3.connect(db_path)
    try:
        before = conn.execute("SELECT COUNT(*) FROM daily_fx_rates").fetchone()[0]
        conn.executemany(
            """INSERT OR IGNORE INTO daily_fx_rates
                 (rate_date, currency_pair, rate, source, uploaded_by_name)
               VALUES (?, ?, ?, ?, ?)""",
            [(d, CURRENCY_PAIR, rows[d], SOURCE, UPLOADED_BY) for d in sorted(rows)],
        )
        conn.commit()
        after = conn.execute("SELECT COUNT(*) FROM daily_fx_rates").fetchone()[0]
    finally:
        conn.close()
    inserted = after - before
    return inserted, len(rows) - inserted


def emit_script(rows: dict) -> str:
    items = ",\n".join(f"    ({d!r}, {rows[d]})" for d in sorted(rows))
    return f'''#!/usr/bin/env python3
"""Self-contained CBU FX backfill — generated by tools/backfill_fx_rates.py.
Run on prod: writes CBU official USD/UZS rates into daily_fx_rates.
INSERT OR IGNORE (preserves user-uploaded rows); tagged source='cbu_official'.
Undo: DELETE FROM daily_fx_rates WHERE source='cbu_official';
"""
import os, sqlite3
DB = os.environ.get("DATABASE_PATH", "/data/catalog.db").replace("sqlite:///", "")
RATES = [
{items}
]
conn = sqlite3.connect(DB)
before = conn.execute("SELECT COUNT(*) FROM daily_fx_rates").fetchone()[0]
conn.executemany(
    "INSERT OR IGNORE INTO daily_fx_rates (rate_date, currency_pair, rate, source, uploaded_by_name) "
    "VALUES (?, 'USD_UZS', ?, 'cbu_official', 'CBU backfill')",
    RATES,
)
conn.commit()
after = conn.execute("SELECT COUNT(*) FROM daily_fx_rates").fetchone()[0]
rng = conn.execute("SELECT MIN(rate_date), MAX(rate_date), COUNT(*) FROM daily_fx_rates").fetchone()
print(f"DB={{DB}} inserted={{after-before}} skipped={{len(RATES)-(after-before)}} "
      f"now_min={{rng[0]}} now_max={{rng[1]}} total={{rng[2]}}")
conn.close()
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", help="SQLite DB path to write into")
    ap.add_argument("--emit-script", action="store_true",
                    help="print a self-contained backfill script (rates embedded)")
    args = ap.parse_args()

    rows = parse_rates()
    if args.emit_script:
        sys.stdout.write(emit_script(rows))
        return
    if not args.db:
        ap.error("provide --db PATH or --emit-script")
    inserted, skipped = apply_to_db(args.db, rows)
    print(f"parsed={len(rows)} inserted={inserted} skipped(existing)={skipped}")


if __name__ == "__main__":
    main()
